language: c
env:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08.0
cache:
  directories:
    - ${HOME}/.opam
before_install:
  - wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.2/opam-2.0.2-x86_64-linux
  - chmod +x ${HOME}/opam
  - export PATH=${HOME}:${PATH}
  - export OPAMYES=1
  - export OPAMJOBS=2
  - opam init --bare --disable-sandboxing
  - opam switch --dry-run ${OCAML_VERSION} 2>/dev/null || opam switch create ${OCAML_VERSION}
install:
  - opam switch ${OCAML_VERSION}
  - opam update --upgrade
  - opam pin add --no-action ocamlformat .
  - opam install --deps-only ocamlformat
script:
  - opam switch ${OCAML_VERSION}
  - opam exec -- make test
  - opam install ocamlformat
